(function() {var implementors = {};
implementors['chemfiles'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='chemfiles/struct.Atom.html' title='chemfiles::Atom'>Atom</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='chemfiles/struct.UnitCell.html' title='chemfiles::UnitCell'>UnitCell</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='chemfiles/struct.Topology.html' title='chemfiles::Topology'>Topology</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='chemfiles/struct.Frame.html' title='chemfiles::Frame'>Frame</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='chemfiles/struct.Trajectory.html' title='chemfiles::Trajectory'>Trajectory</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='chemfiles/struct.Selection.html' title='chemfiles::Selection'>Selection</a>",];implementors['chemfiles'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='chemfiles/struct.Atom.html' title='chemfiles::Atom'>Atom</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='chemfiles/struct.UnitCell.html' title='chemfiles::UnitCell'>UnitCell</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='chemfiles/struct.Topology.html' title='chemfiles::Topology'>Topology</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='chemfiles/struct.Frame.html' title='chemfiles::Frame'>Frame</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='chemfiles/struct.Trajectory.html' title='chemfiles::Trajectory'>Trajectory</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
